name: Auto increment version and merge PR

on:
  issue_comment:
    types: [created]

jobs:
  bump-and-merge:
    if: github.event.comment.body == '/merge'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: refs/pull/${{ github.event.issue.number }}/head

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Squash PR commits
        run: |
          TARGET_BRANCH=$(gh pr view ${{ github.event.issue.number }} --json baseRefName -q .baseRefName)
          echo "Target branch: $TARGET_BRANCH"

          # Rebase onto target branch to avoid out-of-date errors
          git fetch origin $TARGET_BRANCH
          git rebase origin/$TARGET_BRANCH

          # Squash all PR commits into one
          COMMIT_MESSAGES=$(git log origin/$TARGET_BRANCH..HEAD --pretty=format:"%s%n%n%b")
          git reset --soft origin/$TARGET_BRANCH
          git commit -m "$COMMIT_MESSAGES"

      - name: Detect version bump
        id: bump
        run: |
          LAST_MSG=$(git log -1 --pretty=%B)
          echo "Last commit: $LAST_MSG"
          BUMP="patch"
          if echo "$LAST_MSG" | grep -q "BREAKING CHANGE"; then
            BUMP="major"
          elif echo "$LAST_MSG" | grep -q "^feat"; then
            BUMP="minor"
          elif echo "$LAST_MSG" | grep -q "^fix"; then
            BUMP="patch"
          fi
          echo "Bump type: $BUMP"

          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current version: $CURRENT_VERSION"

          case "$BUMP" in
            major) NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$1+=1;$2=0;$3=0;print}') ;;
            minor) NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$2+=1;$3=0;print}') ;;
            patch) NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$3+=1;print}') ;;
          esac

          echo "Version bump ($CURRENT_VERSION) -> ($NEW_VERSION)"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Bump version in pom.xml
        run: |
          mvn --batch-mode versions:set -DnewVersion=$NEW_VERSION
          mvn --batch-mode versions:commit

      - name: Commit Version Bump
        run: |
          git add pom.xml
          git commit -m "chore: Bump version to ${{ env.NEW_VERSION }}"

      - name: Push PR branch
        run: git push --force-with-lease origin HEAD

      - name: Merge PR
        run: |
          gh pr merge ${{ github.event.issue.number }} --squash --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}